### ISSUE TITLE
Create static page for registration

### ISSUE THREAD

**Issue by ilagomatis** [ece470/ece470#1]
# Registration Page
## Description
Create a static page for both patients and doctors to signup. Based on the role selected by the user, a form appears where, they can input information like their first and last name, email address etc. Also a password is set in this stage.
## To-do
- [x] Create button container for role selection
  - [x] Add JavaScript functionality to hide button container and show form
- [x] Create patient form
- [x] Create doctor form
- [ ] Extra Functionality for telephone number

**Comment by ckyriakidis** [comment]
Uploaded in https://github.com/ece470/ece470/commit/75ebf32eb933bc0bbbae6c327c3de9d71aa5c90d under register.html

If possible, I would like to make changes to the **doctor-tel** and **patient-tel** input boxes, so that they use a XXX XXX XXXX format, but I don't know whether that's feasible. I have created some functions and listeners for both input boxes, but at the moment there are problems when removing a character.

**Comment by ckyriakidis** [comment]
I was unable to find a solution for this, closing for now
