### ISSUE TITLE
Create static page for login

### ISSUE THREAD

**Issue by KalliGiannikoglou** [ece470/ece470#2]
# Login Page
## Description
Create a static page for both patients and doctors to login. The user selects their role from the two Radio Buttons, and then input their personal credentials. They can also choose whether they would like to stay signed-in or not. The form also includes a redirection to the Registration Page if the user does not have an account.
## To-do
- [x] Add Radio Buttons for users to choose their role
- [x] Add forms where users can input their login information
- [x] Add "Remember Me" checkbox to keep the user signed-in
- [x] Add Login Button
- [x] Add text to redirect user to Registration Page

**Comment by ckyriakidis** [comment]
Uploaded in https://github.com/ece470/ece470/commit/75ebf32eb933bc0bbbae6c327c3de9d71aa5c90d under login.html

**Comment by ckyriakidis** [comment]
Forgot to move to Done
