### ISSUE TITLE
Create the calendar 

### ISSUE THREAD

**Issue by KalliGiannikoglou** [ece470/ece470#32]
## Description
Create the calendar for patients and health experts and create their basic functionalities.

## TODOs
- [x] display of existing notes
- [x] add new note
- [x] update existing note
- [x] delete note
