### ISSUE TITLE
New Medical Action Static Page

### ISSUE THREAD

**Issue by KalliGiannikoglou** [ece470/ece470#34]
## Description 
In this page, the doctior can search the patient by the AMKA. When found, we print their personal info and the doctor has 3 options: make a diagnosis, write a prescription, perform a medical action. 

- Diagnosis: details of diagnosis
- Prescription: drug code, details (such as instructions), end date of prescription
- Execution of MedAction:  title of action, details, date of execution

## TODOs

- [x] search bar
- [x] card for patient's info
- [x] modal for diagnoses
- [x] modal for prescriptions
- [x] modal for medical actions
