### ISSUE TITLE
Dynamically load table data for Appointments

### ISSUE THREAD

**Issue by KalliGiannikoglou** [ece470/ece470#44]
## Description
Dynamically fill the existing table with the data sent from backend. The data is an array of entries with info for: name, last name, DateTime of the doctors appointments (history + upcoming).

#TODOs
- [x] read data from backend 
- [x] separate date and time from DateTime object 
- [x] add new rows to the table
- [x] load the data in the new rows
