### ISSUE TITLE
Spring Server setup

### ISSUE THREAD

**Issue by amallikopoulou** [ece470/ece470#5]
## TODOs
- [x] Download and setup spring boot (Java)
- [x] Make the Server accesible by the browsers on localhost
- [x] Respond to a random request with a Json
